version: "3.7"

services:

  api:
    build: ./api
    container_name: api
    restart: always
    image: darylou/flaskapp
    environment:
      - APP_NAME=api
    expose:
      - 8080

  auth:
    build: ./authenticate
    container_name: auth
    restart: always
    environment:
      - APP_NAME=auth
    expose:
      - 8081

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"