version: "3.7"

services:

  api:
    build: ./api
    container_name: api
    restart: always
    image: darylou/flaskapp
    environment:
      - APP_NAME=api
    expose:
      - 8080

  auth:
    build: ./authenticate
    container_name: auth
    restart: always
    image: darylou/auth
    environment:
      - APP_NAME=auth
    expose:
      - 8081

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    image: darylou/nginx
    ports:
      - "3030:3030"
  
  nginx-frontend:
    build: ./nginx-frontend
    container_name: nginx-frontend
    restart: always
    image: darylou/nginx-frontend
    ports:
      - "80:80"

  # frontend:
  #   container_name: frontend
  #   build: ./frontend
  #   image: darylou/frontend
  #   volumes:
  #     - '.:/frontend'
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true

  db:
    build: ./postgres
    image: darylou/postgres
    container_name: db
    restart: always
    ports:
      - 5432
    environment:
      POSTGRES_USER: "saas"
      POSTGRES_PASSWORD: "saas"
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
