version: "3.7"

services:

  api:
    build: ./api
    container_name: api
    restart: always
    image: darylou/flaskapp
    environment:
      - APP_NAME=api
      #ADD DB_URL VAR HERE
    expose:
      - 8080

  auth:
    build: ./authenticate
    container_name: auth
    restart: always
    image: darylou/auth
    environment:
      - APP_NAME=auth
    expose:
      - 8081

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    image: darylou/nginx
    ports:
      - "80:80"

  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - '.:/frontend'
      - '/frontend/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "saas"
      POSTGRES_PASSWORD: "saas"

