version: "3.7"

services:

  flask:
    build: ./flask
    container_name: flask
    restart: always
    image: darylou/flaskapp
    environment:
      - APP_NAME=MyFlaskApp
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    image: darylou/nginx
    ports:
      - "80:80"