version: "3.7"

services:

  api:
    build: ./api
    container_name: api
    restart: always
    image: darylou/flaskapp
    environment:
      - APP_NAME=api
    expose:
      - 8080

  auth:
    build: ./authenticate
    container_name: auth
    restart: always
    image: darylou/auth
    environment:
      - APP_NAME=auth
    expose:
      - 8081

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    image: darylou/nginx
    ports:
      - "3030:3030"

  frontend:
    container_name: frontend
    build: ./frontend
    image: darylou/frontend
    volumes:
      - '.:/frontend'
    ports:
      - 80:80
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    build: ./postgres
    image: darylou/postgres
    container_name: db
    restart: always
    ports:
      - 5432
    environment:
      POSTGRES_USER: "saas"
      POSTGRES_PASSWORD: "saas"
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
    - ./postgres/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql