version: "3.7"

services:

  api:
    build: ./api
    container_name: api
    restart: always
    image: darylou/flaskapp
    environment:
      - APP_NAME=api
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    image: darylou/nginx
    ports:
      - "80:80"